name: jenkine bridge
on:
  workflow_call:
    secrets:
      BridgeToken:
        required: true
env:
  SERVER: https://jenkins-bridge-deepin-pre.uniontech.com
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: export

      - uses: actions/checkout@v2
        with:
          repository: "linuxdeepin/jenkins-bridge-client"
          path: jenkins-bridge-client
      - name: Install Client
        run: |
          cd $GITHUB_WORKSPACE/jenkins-bridge-client
          go build .
          sudo install -Dvm755 jenkins-bridge-client -t /usr/bin/
          
      - name: Trigger check job
        id: generate-runid
        env:
          CHANGE_ID: ${{ github.event.pull_request.number }}
        run: |
          echo "::set-output name=RUN_ID::$(jenkins-bridge-client -token ${{ secrets.BridgeToken }} -triggerAbicheck)"
      - name: Wait check finish
        run: |
          jenkins-bridge-client wait -server $SERVER -token ${{ secrets.BridgeToken }} -runid ${{ steps.generate-runid.outputs.RUN_ID }}
          jenkins-bridge-client apipass -server $SERVER -token ${{ secrets.BridgeToken }}
          
      - name: cancelled post runs
        if: cancelled()
        run: |
          jenkins-bridge-client -token "$BRIDGE_TOKEN" -runid "${{ steps.generate-runid.outputs.RUN_ID }}" -cancelBuild
