name: CI
on:
  push:
    branches: [ main ]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${GITHUB_WORKSPACE}
          find ${GITHUB_WORKSPACE}
          bash ".github/workflows/backup-to-gitee.bash"
