name: CI
on:
  push:
    branches: [ main ]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/backup-to-gitee.bash"
          "${GITHUB_WORKSPACE}/.github/backup-to-gitee.bash"
