name: build deb
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: depends
      run: apt update && DEBIAN_FRONTEND=noninteractive apt -y install g++ cmake make libboost-filesystem-dev libboost-program-options-dev devscripts pbuilder aptitude
    - name: build deb
      run: debuild-pbuilder -us -uc -nc
