name: Lint Commit Messages
on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: peeweep-test/action-conventionalcommits-checker@master

