name: Validate-YAML

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize ] 

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: 'yamllint -d "{
          extends: relaxed, rules: {
            new-lines: disable,
            line-length: {max: 120},
            trailing-spaces: {level: warning},
            new-line-at-end-of-file: {level: warning}
          }
        }" .'
      - name: Test GitHub Job Summary
        run: 'echo "| Unit Test   | Result         |
                    | ----------- | -------------- |
                    | Test 1      | :red_circle:   |
                    | Test 2      | :green_circle: |" >> $GITHUB_STEP_SUMMARY'
