name: Validate-YAML

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened ] 

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint .